config/routes.rb
Rails.application.routes.draw do
  
  get '/parks/index' => 'parks#index'
  get '/parks/:id' => 'parks#show'
  post '/parks/create' => 'parks#create'
  get '/parks/:id/edit' => 'parks#edit'
  post '/parks/:id/update' => 'parks#update'
  post '/parks/:id/destroy' => 'parks#destroy'
  
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
#  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  
  resources :microposts do
    resources :likes, only: [:create, :destroy]
  end
  
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    resources :posts, param: :slug
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user,   only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]    # (1) への対応

  def new
  end

  def create
    @user = User.find_by(email: params[:password_reset][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = t('email_sent')
      redirect_to root_url
    else
      flash.now[:danger] = t('email_not_found')
      render 'new'
    end
  end

  def edit
  end
  
  def update
    if params[:user][:password].empty?                  # (3) への対応
      @user.errors.add(:password, :blank)
      render 'edit'
    elsif @user.update_attributes(user_params)          # (4) への対応
      log_in @user
      @user.update_attribute(:reset_digest, nil)
      flash[:success] = t('password_reset2')
      redirect_to @user
    else
      render 'edit'                                     # (2) への対応
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

    # beforeフィルタ

    def get_user
      @user = User.find_by(email: params[:email])
    end

    # 有効なユーザーかどうか確認する
    def valid_user
      unless (@user && @user.activated? &&
              @user.authenticated?(:reset, params[:id]))
        redirect_to root_url
      end
    end
  
    # トークンが期限切れかどうか確認する
    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = t('password_reset_expired')
        redirect_to new_password_reset_url
      end
    end
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<% provide(:title, 'Reset password') %>
<h1><%= t(:password_reset) %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: password_reset_path(params[:id])) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= hidden_field_tag :email, @user.email %>

      <%= f.label t(:password) %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label t(:password_confirmation) %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit t(:password_update), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "Forgot password") %>
<h1><%= t(:forgot_password) %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:password_reset, url: password_resets_path) do |f| %>
      <%= f.label t(:email) %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.submit t(:submit), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>