config/routes.rb
Rails.application.routes.draw do
  
  get '/parks/index' => 'parks#index'
  get '/parks/:id' => 'parks#show'
  post '/parks/create' => 'parks#create'
  get '/parks/:id/edit' => 'parks#edit'
  post '/parks/:id/update' => 'parks#update'
  post '/parks/:id/destroy' => 'parks#destroy'
  
  root   'static_pages#home'
  get    '/help',    to: 'static_pages#help'
  get    '/about',   to: 'static_pages#about'
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
#  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  
  resources :microposts do
    resources :likes, only: [:create, :destroy]
  end
  
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    resources :posts, param: :slug
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<!--
  <small>The app was created by Hiroaki Inoue</small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><a href="URL">News</a></li>
    </ul>
  </nav>
-->
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "SK8RICKS", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to t(:diaries), root_path %></li>
          <li><%= link_to t(:park), parks_index_path %></li>
          <li><%= link_to t(:users), users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t(:account) %><b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to t(:profile), current_user %></li>
              <li><%= link_to t(:setting), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(:log_out), logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(:about), about_path %></li>
          <li><%= link_to t(:login), login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
<!--
    <%= debug(params) if Rails.env.development? %>
-->
  </body>
</html>